apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liveclass

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - redis.yaml
  - deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: liveclass

# Image customization (override during deployment)
images:
  - name: liveclass
    newName: liveclass
    newTag: latest

