apiVersion: v1
kind: Secret
metadata:
  name: liveclass-secrets
  namespace: liveclass
  labels:
    app.kubernetes.io/name: liveclass
type: Opaque
stringData:
  # JWT Secret - CHANGE THIS IN PRODUCTION!
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-k8s"
  JWT_EXPIRY_HOURS: "72"
  
  # Admin credentials (created on first run)
  ADMIN_EMAIL: "admin@liveclass.com"
  ADMIN_PASSWORD: "admin123"
  ADMIN_NAME: "Administrator"

